---
- name: Clone project
  git: repo={{ site.repo }} dest={{ site.path }} version={{ general.branch }} accept_hostkey=yes

- name: Download dependencies
  npm: path={{ site.path }}/web state=present
  sudo: yes

- name: Install Bower globally
  npm: name=bower global=yes
  sudo: yes

- name: Download bower dependencies
  shell: bower install chdir={{ site.path }}/web --allow-root

- name: Build project
  shell: ./node_modules/.bin/gulp build chdir={{ site.path }}/web

