---
- hosts: staging
  sudo: yes
  gather_facts: true

  roles:
    - supervisor
    - keys
    - nginx
    - git
    - nodejs
    - site


  vars:
    general:
      branch: staging
      port: 80
    site:
      name: noon
      path: /var/www/site
      repo: https://github.com/fufeck/noon.git
      user: www-data
      group: www-data


